use strum_macros::EnumIter;

use super::BirdCardColor;
use crate::{{habitat::Habitat, nest::NestType, food::{{BirdCardCost, CostAlternative}}}};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, EnumIter)]
pub enum BirdCard {
  AcornWoodpecker,
  AmericanAvocet,
  AmericanBittern,
  AmericanCoot,
  AmericanCrow,
  AmericanGoldfinch,
  AmericanKestrel,
  AmericanOystercatcher,
  AmericanRedstart,
  AmericanRobin,
  AmericanWhitePelican,
  AmericanWoodcock,
  Anhinga,
  AnnasHummingbird,
  AshThroatedFlycatcher,
  AtlanticPuffin,
  BairdsSparrow,
  BaldEagle,
  BaltimoreOriole,
  BarnOwl,
  BarnSwallow,
  BarredOwl,
  BarrowsGoldeneye,
  BellsVireo,
  BeltedKingfisher,
  BewicksWren,
  BlackSkimmer,
  BlackTern,
  BlackVulture,
  BlackBelliedWhistlingDuck,
  BlackBilledMagpie,
  BlackChinnedHummingbird,
  BlackCrownedNightHeron,
  BlackNeckedStilt,
  BlueGrosbeak,
  BlueJay,
  BlueGrayGnatcatcher,
  BlueWingedWarbler,
  Bobolink,
  Brant,
  BrewersBlackbird,
  BroadWingedHawk,
  BronzedCowbird,
  BrownPelican,
  BrownHeadedCowbird,
  BurrowingOwl,
  Bushtit,
  CaliforniaCondor,
  CaliforniaQuail,
  CanadaGoose,
  Canvasback,
  CarolinaChickadee,
  CarolinaWren,
  CassinsFinch,
  CassinsSparrow,
  CedarWaxwing,
  CeruleanWarbler,
  ChestnutCollaredLongspur,
  ChihuahuanRaven,
  ChimneySwift,
  ChippingSparrow,
  ClarksGrebe,
  ClarksNutcracker,
  CommonGrackle,
  CommonLoon,
  CommonMerganser,
  CommonNighthawk,
  CommonRaven,
  CommonYellowthroat,
  CoopersHawk,
  DarkEyedJunco,
  Dickcissel,
  DoubleCrestedCormorant,
  DownyWoodpecker,
  EasternBluebird,
  EasternKingbird,
  EasternPhoebe,
  EasternScreechOwl,
  FerruginousHawk,
  FishCrow,
  ForstersTern,
  FranklinsGull,
  GoldenEagle,
  GrasshopperSparrow,
  GrayCatbird,
  GreatBlueHeron,
  GreatCrestedFlycatcher,
  GreatEgret,
  GreatHornedOwl,
  GreaterPrairieChicken,
  GreaterRoadrunner,
  GreenHeron,
  HermitThrush,
  HoodedMerganser,
  HoodedWarbler,
  HornedLark,
  HouseFinch,
  HouseWren,
  IncaDove,
  IndigoBunting,
  JuniperTitmouse,
  Killdeer,
  KingRail,
  LazuliBunting,
  LincolnsSparrow,
  LoggerheadShrike,
  Mallard,
  MississippiKite,
  MountainBluebird,
  MountainChickadee,
  MourningDove,
  NorthernBobwhite,
  NorthernCardinal,
  NorthernFlicker,
  NorthernHarrier,
  NorthernMockingbird,
  NorthernShoveler,
  Osprey,
  PaintedBunting,
  PaintedWhitestart,
  PeregrineFalcon,
  PiedBilledGrebe,
  PileatedWoodpecker,
  PineSiskin,
  ProthonotaryWarbler,
  PurpleGallinule,
  PurpleMartin,
  PygmyNuthatch,
  RedCrossbill,
  RedBelliedWoodpecker,
  RedBreastedMerganser,
  RedBreastedNuthatch,
  RedCockadedWoodpecker,
  RedEyedVireo,
  RedHeadedWoodpecker,
  RedShoulderedHawk,
  RedTailedHawk,
  RedWingedBlackbird,
  RingBilledGull,
  RoseBreastedGrosbeak,
  RoseateSpoonbill,
  RubyCrownedKinglet,
  RubyThroatedHummingbird,
  RuddyDuck,
  SandhillCrane,
  SavannahSparrow,
  SaysPhoebe,
  ScaledQuail,
  ScissorTailedFlycatcher,
  SnowyEgret,
  SongSparrow,
  SpottedOwl,
  SpottedSandpiper,
  SpottedTowhee,
  SpraguesPipit,
  StellersJay,
  SwainsonsHawk,
  TreeSwallow,
  TrumpeterSwan,
  TuftedTitmouse,
  TurkeyVulture,
  VauxsSwift,
  VioletGreenSwallow,
  WesternMeadowlark,
  WesternTanager,
  WhiteBreastedNuthatch,
  WhiteCrownedSparrow,
  WhiteFacedIbis,
  WhiteThroatedSwift,
  WhoopingCrane,
  WildTurkey,
  Willet,
  WilsonsSnipe,
  WoodDuck,
  WoodStork,
  YellowBelliedSapsucker,
  YellowBilledCuckoo,
  YellowBreastedChat,
  YellowHeadedBlackbird,
  YellowRumpedWarbler,
}

impl BirdCard {
  pub fn index(&self) -> u16 {
    match self {
      Self::AcornWoodpecker => 1,
      Self::AmericanAvocet => 2,
      Self::AmericanBittern => 3,
      Self::AmericanCoot => 4,
      Self::AmericanCrow => 5,
      Self::AmericanGoldfinch => 6,
      Self::AmericanKestrel => 7,
      Self::AmericanOystercatcher => 8,
      Self::AmericanRedstart => 9,
      Self::AmericanRobin => 10,
      Self::AmericanWhitePelican => 11,
      Self::AmericanWoodcock => 12,
      Self::Anhinga => 13,
      Self::AnnasHummingbird => 14,
      Self::AshThroatedFlycatcher => 15,
      Self::AtlanticPuffin => 18,
      Self::BairdsSparrow => 30,
      Self::BaldEagle => 31,
      Self::BaltimoreOriole => 32,
      Self::BarnOwl => 33,
      Self::BarnSwallow => 34,
      Self::BarredOwl => 35,
      Self::BarrowsGoldeneye => 36,
      Self::BellsVireo => 39,
      Self::BeltedKingfisher => 40,
      Self::BewicksWren => 41,
      Self::BlackSkimmer => 45,
      Self::BlackTern => 48,
      Self::BlackVulture => 49,
      Self::BlackBelliedWhistlingDuck => 51,
      Self::BlackBilledMagpie => 52,
      Self::BlackChinnedHummingbird => 53,
      Self::BlackCrownedNightHeron => 54,
      Self::BlackNeckedStilt => 57,
      Self::BlueGrosbeak => 61,
      Self::BlueJay => 62,
      Self::BlueGrayGnatcatcher => 64,
      Self::BlueWingedWarbler => 65,
      Self::Bobolink => 68,
      Self::Brant => 72,
      Self::BrewersBlackbird => 73,
      Self::BroadWingedHawk => 74,
      Self::BronzedCowbird => 76,
      Self::BrownPelican => 78,
      Self::BrownHeadedCowbird => 80,
      Self::BurrowingOwl => 83,
      Self::Bushtit => 84,
      Self::CaliforniaCondor => 85,
      Self::CaliforniaQuail => 86,
      Self::CanadaGoose => 87,
      Self::Canvasback => 88,
      Self::CarolinaChickadee => 89,
      Self::CarolinaWren => 90,
      Self::CassinsFinch => 92,
      Self::CassinsSparrow => 93,
      Self::CedarWaxwing => 94,
      Self::CeruleanWarbler => 95,
      Self::ChestnutCollaredLongspur => 97,
      Self::ChihuahuanRaven => 98,
      Self::ChimneySwift => 99,
      Self::ChippingSparrow => 100,
      Self::ClarksGrebe => 101,
      Self::ClarksNutcracker => 102,
      Self::CommonGrackle => 111,
      Self::CommonLoon => 116,
      Self::CommonMerganser => 117,
      Self::CommonNighthawk => 120,
      Self::CommonRaven => 122,
      Self::CommonYellowthroat => 128,
      Self::CoopersHawk => 129,
      Self::DarkEyedJunco => 137,
      Self::Dickcissel => 140,
      Self::DoubleCrestedCormorant => 141,
      Self::DownyWoodpecker => 142,
      Self::EasternBluebird => 144,
      Self::EasternKingbird => 146,
      Self::EasternPhoebe => 147,
      Self::EasternScreechOwl => 149,
      Self::FerruginousHawk => 175,
      Self::FishCrow => 177,
      Self::ForstersTern => 179,
      Self::FranklinsGull => 180,
      Self::GoldenEagle => 183,
      Self::GrasshopperSparrow => 189,
      Self::GrayCatbird => 190,
      Self::GreatBlueHeron => 192,
      Self::GreatCrestedFlycatcher => 194,
      Self::GreatEgret => 196,
      Self::GreatHornedOwl => 198,
      Self::GreaterPrairieChicken => 204,
      Self::GreaterRoadrunner => 205,
      Self::GreenHeron => 207,
      Self::HermitThrush => 219,
      Self::HoodedMerganser => 222,
      Self::HoodedWarbler => 223,
      Self::HornedLark => 224,
      Self::HouseFinch => 228,
      Self::HouseWren => 230,
      Self::IncaDove => 232,
      Self::IndigoBunting => 235,
      Self::JuniperTitmouse => 236,
      Self::Killdeer => 241,
      Self::KingRail => 242,
      Self::LazuliBunting => 246,
      Self::LincolnsSparrow => 250,
      Self::LoggerheadShrike => 258,
      Self::Mallard => 262,
      Self::MississippiKite => 268,
      Self::MountainBluebird => 272,
      Self::MountainChickadee => 273,
      Self::MourningDove => 274,
      Self::NorthernBobwhite => 280,
      Self::NorthernCardinal => 281,
      Self::NorthernFlicker => 282,
      Self::NorthernHarrier => 285,
      Self::NorthernMockingbird => 286,
      Self::NorthernShoveler => 287,
      Self::Osprey => 292,
      Self::PaintedBunting => 294,
      Self::PaintedWhitestart => 295,
      Self::PeregrineFalcon => 298,
      Self::PiedBilledGrebe => 302,
      Self::PileatedWoodpecker => 303,
      Self::PineSiskin => 304,
      Self::ProthonotaryWarbler => 309,
      Self::PurpleGallinule => 311,
      Self::PurpleMartin => 313,
      Self::PygmyNuthatch => 314,
      Self::RedCrossbill => 317,
      Self::RedBelliedWoodpecker => 324,
      Self::RedBreastedMerganser => 325,
      Self::RedBreastedNuthatch => 326,
      Self::RedCockadedWoodpecker => 328,
      Self::RedEyedVireo => 330,
      Self::RedHeadedWoodpecker => 331,
      Self::RedShoulderedHawk => 334,
      Self::RedTailedHawk => 335,
      Self::RedWingedBlackbird => 338,
      Self::RingBilledGull => 342,
      Self::RoseBreastedGrosbeak => 345,
      Self::RoseateSpoonbill => 347,
      Self::RubyCrownedKinglet => 350,
      Self::RubyThroatedHummingbird => 351,
      Self::RuddyDuck => 352,
      Self::SandhillCrane => 359,
      Self::SavannahSparrow => 362,
      Self::SaysPhoebe => 364,
      Self::ScaledQuail => 365,
      Self::ScissorTailedFlycatcher => 367,
      Self::SnowyEgret => 373,
      Self::SongSparrow => 375,
      Self::SpottedOwl => 383,
      Self::SpottedSandpiper => 384,
      Self::SpottedTowhee => 385,
      Self::SpraguesPipit => 386,
      Self::StellersJay => 390,
      Self::SwainsonsHawk => 395,
      Self::TreeSwallow => 398,
      Self::TrumpeterSwan => 400,
      Self::TuftedTitmouse => 401,
      Self::TurkeyVulture => 403,
      Self::VauxsSwift => 405,
      Self::VioletGreenSwallow => 408,
      Self::WesternMeadowlark => 411,
      Self::WesternTanager => 412,
      Self::WhiteBreastedNuthatch => 417,
      Self::WhiteCrownedSparrow => 421,
      Self::WhiteFacedIbis => 423,
      Self::WhiteThroatedSwift => 427,
      Self::WhoopingCrane => 428,
      Self::WildTurkey => 429,
      Self::Willet => 430,
      Self::WilsonsSnipe => 433,
      Self::WoodDuck => 435,
      Self::WoodStork => 436,
      Self::YellowBelliedSapsucker => 439,
      Self::YellowBilledCuckoo => 440,
      Self::YellowBreastedChat => 441,
      Self::YellowHeadedBlackbird => 442,
      Self::YellowRumpedWarbler => 443,
    }
  }

  pub fn name(&self) -> &'static str {
    match self {
      Self::AcornWoodpecker => "Acorn Woodpecker",
      Self::AmericanAvocet => "American Avocet",
      Self::AmericanBittern => "American Bittern",
      Self::AmericanCoot => "American Coot",
      Self::AmericanCrow => "American Crow",
      Self::AmericanGoldfinch => "American Goldfinch",
      Self::AmericanKestrel => "American Kestrel",
      Self::AmericanOystercatcher => "American Oystercatcher",
      Self::AmericanRedstart => "American Redstart",
      Self::AmericanRobin => "American Robin",
      Self::AmericanWhitePelican => "American White Pelican",
      Self::AmericanWoodcock => "American Woodcock",
      Self::Anhinga => "Anhinga",
      Self::AnnasHummingbird => "Anna's Hummingbird",
      Self::AshThroatedFlycatcher => "Ash-Throated Flycatcher",
      Self::AtlanticPuffin => "Atlantic Puffin",
      Self::BairdsSparrow => "Baird's Sparrow",
      Self::BaldEagle => "Bald Eagle",
      Self::BaltimoreOriole => "Baltimore Oriole",
      Self::BarnOwl => "Barn Owl",
      Self::BarnSwallow => "Barn Swallow",
      Self::BarredOwl => "Barred Owl",
      Self::BarrowsGoldeneye => "Barrow's Goldeneye",
      Self::BellsVireo => "Bell's Vireo",
      Self::BeltedKingfisher => "Belted Kingfisher",
      Self::BewicksWren => "Bewick's Wren",
      Self::BlackSkimmer => "Black Skimmer",
      Self::BlackTern => "Black Tern",
      Self::BlackVulture => "Black Vulture",
      Self::BlackBelliedWhistlingDuck => "Black-Bellied Whistling-Duck",
      Self::BlackBilledMagpie => "Black-Billed Magpie",
      Self::BlackChinnedHummingbird => "Black-Chinned Hummingbird",
      Self::BlackCrownedNightHeron => "Black-Crowned Night-Heron",
      Self::BlackNeckedStilt => "Black-Necked Stilt",
      Self::BlueGrosbeak => "Blue Grosbeak",
      Self::BlueJay => "Blue Jay",
      Self::BlueGrayGnatcatcher => "Blue-Gray Gnatcatcher",
      Self::BlueWingedWarbler => "Blue-Winged Warbler",
      Self::Bobolink => "Bobolink",
      Self::Brant => "Brant",
      Self::BrewersBlackbird => "Brewer's Blackbird",
      Self::BroadWingedHawk => "Broad-Winged Hawk",
      Self::BronzedCowbird => "Bronzed Cowbird",
      Self::BrownPelican => "Brown Pelican",
      Self::BrownHeadedCowbird => "Brown-Headed Cowbird",
      Self::BurrowingOwl => "Burrowing Owl",
      Self::Bushtit => "Bushtit",
      Self::CaliforniaCondor => "California Condor",
      Self::CaliforniaQuail => "California Quail",
      Self::CanadaGoose => "Canada Goose",
      Self::Canvasback => "Canvasback",
      Self::CarolinaChickadee => "Carolina Chickadee",
      Self::CarolinaWren => "Carolina Wren",
      Self::CassinsFinch => "Cassin's Finch",
      Self::CassinsSparrow => "Cassin's Sparrow",
      Self::CedarWaxwing => "Cedar Waxwing",
      Self::CeruleanWarbler => "Cerulean Warbler",
      Self::ChestnutCollaredLongspur => "Chestnut-Collared Longspur",
      Self::ChihuahuanRaven => "Chihuahuan Raven",
      Self::ChimneySwift => "Chimney Swift",
      Self::ChippingSparrow => "Chipping Sparrow",
      Self::ClarksGrebe => "Clark's Grebe",
      Self::ClarksNutcracker => "Clark's Nutcracker",
      Self::CommonGrackle => "Common Grackle",
      Self::CommonLoon => "Common Loon",
      Self::CommonMerganser => "Common Merganser",
      Self::CommonNighthawk => "Common Nighthawk",
      Self::CommonRaven => "Common Raven",
      Self::CommonYellowthroat => "Common Yellowthroat",
      Self::CoopersHawk => "Cooper's Hawk",
      Self::DarkEyedJunco => "Dark-Eyed Junco",
      Self::Dickcissel => "Dickcissel",
      Self::DoubleCrestedCormorant => "Double-Crested Cormorant",
      Self::DownyWoodpecker => "Downy Woodpecker",
      Self::EasternBluebird => "Eastern Bluebird",
      Self::EasternKingbird => "Eastern Kingbird",
      Self::EasternPhoebe => "Eastern Phoebe",
      Self::EasternScreechOwl => "Eastern Screech-Owl",
      Self::FerruginousHawk => "Ferruginous Hawk",
      Self::FishCrow => "Fish Crow",
      Self::ForstersTern => "Forster's Tern",
      Self::FranklinsGull => "Franklin's Gull",
      Self::GoldenEagle => "Golden Eagle",
      Self::GrasshopperSparrow => "Grasshopper Sparrow",
      Self::GrayCatbird => "Gray Catbird",
      Self::GreatBlueHeron => "Great Blue Heron",
      Self::GreatCrestedFlycatcher => "Great Crested Flycatcher",
      Self::GreatEgret => "Great Egret",
      Self::GreatHornedOwl => "Great Horned Owl",
      Self::GreaterPrairieChicken => "Greater Prairie-Chicken",
      Self::GreaterRoadrunner => "Greater Roadrunner",
      Self::GreenHeron => "Green Heron",
      Self::HermitThrush => "Hermit Thrush",
      Self::HoodedMerganser => "Hooded Merganser",
      Self::HoodedWarbler => "Hooded Warbler",
      Self::HornedLark => "Horned Lark",
      Self::HouseFinch => "House Finch",
      Self::HouseWren => "House Wren",
      Self::IncaDove => "Inca Dove",
      Self::IndigoBunting => "Indigo Bunting",
      Self::JuniperTitmouse => "Juniper Titmouse",
      Self::Killdeer => "Killdeer",
      Self::KingRail => "King Rail",
      Self::LazuliBunting => "Lazuli Bunting",
      Self::LincolnsSparrow => "Lincoln's Sparrow",
      Self::LoggerheadShrike => "Loggerhead Shrike",
      Self::Mallard => "Mallard",
      Self::MississippiKite => "Mississippi Kite",
      Self::MountainBluebird => "Mountain Bluebird",
      Self::MountainChickadee => "Mountain Chickadee",
      Self::MourningDove => "Mourning Dove",
      Self::NorthernBobwhite => "Northern Bobwhite",
      Self::NorthernCardinal => "Northern Cardinal",
      Self::NorthernFlicker => "Northern Flicker",
      Self::NorthernHarrier => "Northern Harrier",
      Self::NorthernMockingbird => "Northern Mockingbird",
      Self::NorthernShoveler => "Northern Shoveler",
      Self::Osprey => "Osprey",
      Self::PaintedBunting => "Painted Bunting",
      Self::PaintedWhitestart => "Painted Whitestart",
      Self::PeregrineFalcon => "Peregrine Falcon",
      Self::PiedBilledGrebe => "Pied-Billed Grebe",
      Self::PileatedWoodpecker => "Pileated Woodpecker",
      Self::PineSiskin => "Pine Siskin",
      Self::ProthonotaryWarbler => "Prothonotary Warbler",
      Self::PurpleGallinule => "Purple Gallinule",
      Self::PurpleMartin => "Purple Martin",
      Self::PygmyNuthatch => "Pygmy Nuthatch",
      Self::RedCrossbill => "Red Crossbill",
      Self::RedBelliedWoodpecker => "Red-Bellied Woodpecker",
      Self::RedBreastedMerganser => "Red-Breasted Merganser",
      Self::RedBreastedNuthatch => "Red-Breasted Nuthatch",
      Self::RedCockadedWoodpecker => "Red-Cockaded Woodpecker",
      Self::RedEyedVireo => "Red-Eyed Vireo",
      Self::RedHeadedWoodpecker => "Red-Headed Woodpecker",
      Self::RedShoulderedHawk => "Red-Shouldered Hawk",
      Self::RedTailedHawk => "Red-Tailed Hawk",
      Self::RedWingedBlackbird => "Red-Winged Blackbird",
      Self::RingBilledGull => "Ring-Billed Gull",
      Self::RoseBreastedGrosbeak => "Rose-Breasted Grosbeak",
      Self::RoseateSpoonbill => "Roseate Spoonbill",
      Self::RubyCrownedKinglet => "Ruby-Crowned Kinglet",
      Self::RubyThroatedHummingbird => "Ruby-Throated Hummingbird",
      Self::RuddyDuck => "Ruddy Duck",
      Self::SandhillCrane => "Sandhill Crane",
      Self::SavannahSparrow => "Savannah Sparrow",
      Self::SaysPhoebe => "Say's Phoebe",
      Self::ScaledQuail => "Scaled Quail",
      Self::ScissorTailedFlycatcher => "Scissor-Tailed Flycatcher",
      Self::SnowyEgret => "Snowy Egret",
      Self::SongSparrow => "Song Sparrow",
      Self::SpottedOwl => "Spotted Owl",
      Self::SpottedSandpiper => "Spotted Sandpiper",
      Self::SpottedTowhee => "Spotted Towhee",
      Self::SpraguesPipit => "Sprague's Pipit",
      Self::StellersJay => "Steller's Jay",
      Self::SwainsonsHawk => "Swainson's Hawk",
      Self::TreeSwallow => "Tree Swallow",
      Self::TrumpeterSwan => "Trumpeter Swan",
      Self::TuftedTitmouse => "Tufted Titmouse",
      Self::TurkeyVulture => "Turkey Vulture",
      Self::VauxsSwift => "Vaux's Swift",
      Self::VioletGreenSwallow => "Violet-Green Swallow",
      Self::WesternMeadowlark => "Western Meadowlark",
      Self::WesternTanager => "Western Tanager",
      Self::WhiteBreastedNuthatch => "White-Breasted Nuthatch",
      Self::WhiteCrownedSparrow => "White-Crowned Sparrow",
      Self::WhiteFacedIbis => "White-Faced Ibis",
      Self::WhiteThroatedSwift => "White-Throated Swift",
      Self::WhoopingCrane => "Whooping Crane",
      Self::WildTurkey => "Wild Turkey",
      Self::Willet => "Willet",
      Self::WilsonsSnipe => "Wilson's Snipe",
      Self::WoodDuck => "Wood Duck",
      Self::WoodStork => "Wood Stork",
      Self::YellowBelliedSapsucker => "Yellow-Bellied Sapsucker",
      Self::YellowBilledCuckoo => "Yellow-Billed Cuckoo",
      Self::YellowBreastedChat => "Yellow-Breasted Chat",
      Self::YellowHeadedBlackbird => "Yellow-Headed Blackbird",
      Self::YellowRumpedWarbler => "Yellow-Rumped Warbler",
    }
  }

  pub fn cost(&self) -> &'static BirdCardCost {
    match self {
      Self::AcornWoodpecker => &([None, Some(3), None, None, None], 3, CostAlternative::No),
      Self::AmericanAvocet => &([Some(2), Some(1), None, None, None], 3, CostAlternative::No),
      Self::AmericanBittern => &([Some(1), None, Some(1), None, Some(1)], 3, CostAlternative::No),
      Self::AmericanCoot => &([None, Some(1), None, None, None], 2, CostAlternative::No),
      Self::AmericanCrow => &([None, None, None, None, None], 1, CostAlternative::No),
      Self::AmericanGoldfinch => &([None, Some(2), None, None, None], 2, CostAlternative::No),
      Self::AmericanKestrel => &([Some(1), None, None, None, Some(1)], 2, CostAlternative::No),
      Self::AmericanOystercatcher => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::AmericanRedstart => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::AmericanRobin => &([Some(1), None, None, Some(1), None], 1, CostAlternative::Yes),
      Self::AmericanWhitePelican => &([None, None, Some(2), None, None], 2, CostAlternative::No),
      Self::AmericanWoodcock => &([Some(2), Some(1), None, None, None], 3, CostAlternative::No),
      Self::Anhinga => &([None, None, Some(2), None, None], 2, CostAlternative::No),
      Self::AnnasHummingbird => &([None, None, None, None, None], 1, CostAlternative::No),
      Self::AshThroatedFlycatcher => &([Some(2), None, None, Some(1), None], 3, CostAlternative::No),
      Self::AtlanticPuffin => &([None, None, Some(3), None, None], 3, CostAlternative::No),
      Self::BairdsSparrow => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::BaldEagle => &([None, None, Some(2), None, Some(1)], 3, CostAlternative::No),
      Self::BaltimoreOriole => &([Some(1), None, None, Some(2), None], 3, CostAlternative::No),
      Self::BarnOwl => &([None, None, None, None, Some(2)], 2, CostAlternative::No),
      Self::BarnSwallow => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::BarredOwl => &([None, None, None, None, Some(1)], 1, CostAlternative::No),
      Self::BarrowsGoldeneye => &([Some(1), Some(1), Some(1), None, None], 3, CostAlternative::No),
      Self::BellsVireo => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::BeltedKingfisher => &([None, None, Some(1), None, None], 2, CostAlternative::No),
      Self::BewicksWren => &([Some(2), Some(1), None, None, None], 3, CostAlternative::No),
      Self::BlackSkimmer => &([None, None, Some(2), None, None], 2, CostAlternative::No),
      Self::BlackTern => &([Some(1), None, Some(1), None, None], 1, CostAlternative::Yes),
      Self::BlackVulture => &([None, None, None, None, None], 0, CostAlternative::No),
      Self::BlackBelliedWhistlingDuck => &([None, Some(2), None, None, None], 2, CostAlternative::No),
      Self::BlackBilledMagpie => &([None, None, None, None, None], 2, CostAlternative::No),
      Self::BlackChinnedHummingbird => &([None, None, None, None, None], 1, CostAlternative::No),
      Self::BlackCrownedNightHeron => &([Some(1), None, Some(1), None, Some(1)], 3, CostAlternative::No),
      Self::BlackNeckedStilt => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::BlueGrosbeak => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::BlueJay => &([None, Some(1), None, None, None], 2, CostAlternative::No),
      Self::BlueGrayGnatcatcher => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::BlueWingedWarbler => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::Bobolink => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::Brant => &([None, Some(1), None, None, None], 2, CostAlternative::No),
      Self::BrewersBlackbird => &([None, Some(1), None, None, None], 2, CostAlternative::No),
      Self::BroadWingedHawk => &([None, None, None, None, Some(1)], 1, CostAlternative::No),
      Self::BronzedCowbird => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::BrownPelican => &([None, None, Some(2), None, None], 2, CostAlternative::No),
      Self::BrownHeadedCowbird => &([None, Some(1), None, None, None], 1, CostAlternative::No),
      Self::BurrowingOwl => &([Some(1), None, None, None, Some(1)], 2, CostAlternative::No),
      Self::Bushtit => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::CaliforniaCondor => &([None, None, None, None, None], 0, CostAlternative::No),
      Self::CaliforniaQuail => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::CanadaGoose => &([None, Some(2), None, None, None], 2, CostAlternative::No),
      Self::Canvasback => &([None, Some(1), None, None, None], 2, CostAlternative::No),
      Self::CarolinaChickadee => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::CarolinaWren => &([Some(1), None, None, Some(1), None], 1, CostAlternative::Yes),
      Self::CassinsFinch => &([None, Some(1), None, Some(1), None], 2, CostAlternative::No),
      Self::CassinsSparrow => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::CedarWaxwing => &([None, None, None, Some(2), None], 2, CostAlternative::No),
      Self::CeruleanWarbler => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::ChestnutCollaredLongspur => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::ChihuahuanRaven => &([None, None, None, None, Some(1)], 3, CostAlternative::No),
      Self::ChimneySwift => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::ChippingSparrow => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::ClarksGrebe => &([None, None, Some(1), None, None], 1, CostAlternative::No),
      Self::ClarksNutcracker => &([None, Some(2), None, None, None], 3, CostAlternative::No),
      Self::CommonGrackle => &([None, Some(1), None, None, None], 2, CostAlternative::No),
      Self::CommonLoon => &([None, None, Some(1), None, None], 2, CostAlternative::No),
      Self::CommonMerganser => &([None, None, Some(1), None, None], 2, CostAlternative::No),
      Self::CommonNighthawk => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::CommonRaven => &([None, None, None, None, Some(1)], 3, CostAlternative::No),
      Self::CommonYellowthroat => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::CoopersHawk => &([None, None, None, None, Some(1)], 1, CostAlternative::No),
      Self::DarkEyedJunco => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::Dickcissel => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::DoubleCrestedCormorant => &([None, None, Some(1), None, None], 2, CostAlternative::No),
      Self::DownyWoodpecker => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
      Self::EasternBluebird => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::EasternKingbird => &([Some(1), None, None, Some(1), None], 1, CostAlternative::Yes),
      Self::EasternPhoebe => &([Some(1), None, None, Some(1), None], 1, CostAlternative::Yes),
      Self::EasternScreechOwl => &([Some(1), None, None, None, Some(1)], 1, CostAlternative::Yes),
      Self::FerruginousHawk => &([None, None, None, None, Some(2)], 2, CostAlternative::No),
      Self::FishCrow => &([None, None, Some(1), None, None], 2, CostAlternative::No),
      Self::ForstersTern => &([Some(1), None, Some(1), None, None], 1, CostAlternative::Yes),
      Self::FranklinsGull => &([None, None, Some(1), None, None], 2, CostAlternative::No),
      Self::GoldenEagle => &([None, None, None, None, Some(3)], 3, CostAlternative::No),
      Self::GrasshopperSparrow => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::GrayCatbird => &([Some(1), None, None, Some(2), None], 3, CostAlternative::No),
      Self::GreatBlueHeron => &([Some(1), None, Some(1), None, None], 2, CostAlternative::No),
      Self::GreatCrestedFlycatcher => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::GreatEgret => &([None, None, Some(2), None, Some(1)], 3, CostAlternative::No),
      Self::GreatHornedOwl => &([None, None, None, None, Some(3)], 3, CostAlternative::No),
      Self::GreaterPrairieChicken => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::GreaterRoadrunner => &([Some(1), None, None, None, Some(1)], 3, CostAlternative::No),
      Self::GreenHeron => &([Some(1), None, Some(1), None, None], 1, CostAlternative::Yes),
      Self::HermitThrush => &([Some(1), None, None, Some(2), None], 3, CostAlternative::No),
      Self::HoodedMerganser => &([Some(1), None, Some(1), None, None], 2, CostAlternative::No),
      Self::HoodedWarbler => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::HornedLark => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::HouseFinch => &([None, Some(1), None, Some(1), None], 2, CostAlternative::No),
      Self::HouseWren => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::IncaDove => &([None, Some(2), None, None, None], 2, CostAlternative::No),
      Self::IndigoBunting => &([Some(1), Some(1), None, Some(1), None], 3, CostAlternative::No),
      Self::JuniperTitmouse => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::Killdeer => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::KingRail => &([Some(1), None, Some(1), None, None], 3, CostAlternative::No),
      Self::LazuliBunting => &([Some(1), Some(1), None, Some(1), None], 3, CostAlternative::No),
      Self::LincolnsSparrow => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::LoggerheadShrike => &([Some(1), None, None, None, Some(1)], 2, CostAlternative::No),
      Self::Mallard => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::MississippiKite => &([Some(1), None, None, None, Some(1)], 1, CostAlternative::Yes),
      Self::MountainBluebird => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::MountainChickadee => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::MourningDove => &([None, Some(1), None, None, None], 1, CostAlternative::No),
      Self::NorthernBobwhite => &([None, Some(3), None, None, None], 3, CostAlternative::No),
      Self::NorthernCardinal => &([None, Some(1), None, Some(1), None], 2, CostAlternative::No),
      Self::NorthernFlicker => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
      Self::NorthernHarrier => &([None, None, None, None, Some(1)], 1, CostAlternative::No),
      Self::NorthernMockingbird => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::NorthernShoveler => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::Osprey => &([None, None, Some(1), None, None], 1, CostAlternative::No),
      Self::PaintedBunting => &([Some(1), Some(2), None, None, None], 3, CostAlternative::No),
      Self::PaintedWhitestart => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::PeregrineFalcon => &([None, None, None, None, Some(2)], 2, CostAlternative::No),
      Self::PiedBilledGrebe => &([Some(1), None, Some(1), None, None], 1, CostAlternative::Yes),
      Self::PileatedWoodpecker => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::PineSiskin => &([None, Some(2), None, None, None], 2, CostAlternative::No),
      Self::ProthonotaryWarbler => &([Some(2), Some(1), None, None, None], 3, CostAlternative::No),
      Self::PurpleGallinule => &([None, Some(1), None, Some(1), None], 3, CostAlternative::No),
      Self::PurpleMartin => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::PygmyNuthatch => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::RedCrossbill => &([None, Some(2), None, None, None], 2, CostAlternative::No),
      Self::RedBelliedWoodpecker => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::RedBreastedMerganser => &([Some(1), None, Some(1), None, None], 2, CostAlternative::No),
      Self::RedBreastedNuthatch => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::RedCockadedWoodpecker => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::RedEyedVireo => &([Some(1), None, None, Some(1), None], 1, CostAlternative::Yes),
      Self::RedHeadedWoodpecker => &([Some(1), Some(1), None, None, None], 3, CostAlternative::No),
      Self::RedShoulderedHawk => &([None, None, None, None, Some(1)], 1, CostAlternative::No),
      Self::RedTailedHawk => &([None, None, None, None, Some(2)], 2, CostAlternative::No),
      Self::RedWingedBlackbird => &([None, Some(1), None, None, None], 1, CostAlternative::No),
      Self::RingBilledGull => &([None, None, None, None, None], 2, CostAlternative::No),
      Self::RoseBreastedGrosbeak => &([Some(1), Some(1), None, Some(1), None], 3, CostAlternative::No),
      Self::RoseateSpoonbill => &([Some(1), Some(1), Some(1), None, None], 3, CostAlternative::No),
      Self::RubyCrownedKinglet => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
      Self::RubyThroatedHummingbird => &([None, None, None, None, None], 1, CostAlternative::No),
      Self::RuddyDuck => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::SandhillCrane => &([None, Some(2), None, None, None], 3, CostAlternative::No),
      Self::SavannahSparrow => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::SaysPhoebe => &([Some(3), None, None, None, None], 3, CostAlternative::No),
      Self::ScaledQuail => &([None, Some(1), None, None, None], 1, CostAlternative::No),
      Self::ScissorTailedFlycatcher => &([Some(2), None, None, Some(1), None], 3, CostAlternative::No),
      Self::SnowyEgret => &([Some(1), None, Some(1), None, None], 1, CostAlternative::Yes),
      Self::SongSparrow => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
      Self::SpottedOwl => &([None, None, None, None, Some(2)], 2, CostAlternative::No),
      Self::SpottedSandpiper => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::SpottedTowhee => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
      Self::SpraguesPipit => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::StellersJay => &([None, Some(2), None, None, None], 3, CostAlternative::No),
      Self::SwainsonsHawk => &([Some(1), None, None, None, Some(1)], 2, CostAlternative::No),
      Self::TreeSwallow => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::TrumpeterSwan => &([None, Some(2), None, None, None], 3, CostAlternative::No),
      Self::TuftedTitmouse => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
      Self::TurkeyVulture => &([None, None, None, None, None], 0, CostAlternative::No),
      Self::VauxsSwift => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::VioletGreenSwallow => &([Some(2), None, None, None, None], 2, CostAlternative::No),
      Self::WesternMeadowlark => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::WesternTanager => &([Some(2), None, None, Some(1), None], 3, CostAlternative::No),
      Self::WhiteBreastedNuthatch => &([Some(1), Some(1), None, None, None], 1, CostAlternative::Yes),
      Self::WhiteCrownedSparrow => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::WhiteFacedIbis => &([Some(2), None, Some(1), None, None], 3, CostAlternative::No),
      Self::WhiteThroatedSwift => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::WhoopingCrane => &([None, None, None, None, None], 3, CostAlternative::No),
      Self::WildTurkey => &([None, Some(2), None, Some(1), None], 3, CostAlternative::No),
      Self::Willet => &([Some(1), None, Some(1), None, None], 1, CostAlternative::Yes),
      Self::WilsonsSnipe => &([Some(1), None, None, None, None], 1, CostAlternative::No),
      Self::WoodDuck => &([None, Some(2), None, Some(1), None], 3, CostAlternative::No),
      Self::WoodStork => &([None, None, Some(1), None, Some(1)], 3, CostAlternative::No),
      Self::YellowBelliedSapsucker => &([Some(1), None, None, Some(1), None], 2, CostAlternative::No),
      Self::YellowBilledCuckoo => &([Some(2), None, None, None, None], 3, CostAlternative::No),
      Self::YellowBreastedChat => &([Some(1), None, None, Some(2), None], 3, CostAlternative::No),
      Self::YellowHeadedBlackbird => &([Some(1), Some(1), None, None, None], 2, CostAlternative::No),
      Self::YellowRumpedWarbler => &([Some(1), Some(1), None, Some(1), None], 1, CostAlternative::Yes),
    }
  }

  pub fn color(&self) -> &BirdCardColor {
    match self {
      Self::AcornWoodpecker => &BirdCardColor::Brown,
      Self::AmericanAvocet => &BirdCardColor::Pink,
      Self::AmericanBittern => &BirdCardColor::Brown,
      Self::AmericanCoot => &BirdCardColor::Brown,
      Self::AmericanCrow => &BirdCardColor::Brown,
      Self::AmericanGoldfinch => &BirdCardColor::White,
      Self::AmericanKestrel => &BirdCardColor::Brown,
      Self::AmericanOystercatcher => &BirdCardColor::White,
      Self::AmericanRedstart => &BirdCardColor::Brown,
      Self::AmericanRobin => &BirdCardColor::Brown,
      Self::AmericanWhitePelican => &BirdCardColor::Brown,
      Self::AmericanWoodcock => &BirdCardColor::None,
      Self::Anhinga => &BirdCardColor::Brown,
      Self::AnnasHummingbird => &BirdCardColor::Brown,
      Self::AshThroatedFlycatcher => &BirdCardColor::White,
      Self::AtlanticPuffin => &BirdCardColor::White,
      Self::BairdsSparrow => &BirdCardColor::Brown,
      Self::BaldEagle => &BirdCardColor::White,
      Self::BaltimoreOriole => &BirdCardColor::Brown,
      Self::BarnOwl => &BirdCardColor::Brown,
      Self::BarnSwallow => &BirdCardColor::Brown,
      Self::BarredOwl => &BirdCardColor::Brown,
      Self::BarrowsGoldeneye => &BirdCardColor::Pink,
      Self::BellsVireo => &BirdCardColor::White,
      Self::BeltedKingfisher => &BirdCardColor::Pink,
      Self::BewicksWren => &BirdCardColor::Brown,
      Self::BlackSkimmer => &BirdCardColor::Brown,
      Self::BlackTern => &BirdCardColor::Brown,
      Self::BlackVulture => &BirdCardColor::Pink,
      Self::BlackBelliedWhistlingDuck => &BirdCardColor::Brown,
      Self::BlackBilledMagpie => &BirdCardColor::Pink,
      Self::BlackChinnedHummingbird => &BirdCardColor::Brown,
      Self::BlackCrownedNightHeron => &BirdCardColor::Brown,
      Self::BlackNeckedStilt => &BirdCardColor::White,
      Self::BlueGrosbeak => &BirdCardColor::Brown,
      Self::BlueJay => &BirdCardColor::Brown,
      Self::BlueGrayGnatcatcher => &BirdCardColor::Brown,
      Self::BlueWingedWarbler => &BirdCardColor::None,
      Self::Bobolink => &BirdCardColor::White,
      Self::Brant => &BirdCardColor::White,
      Self::BrewersBlackbird => &BirdCardColor::Brown,
      Self::BroadWingedHawk => &BirdCardColor::Brown,
      Self::BronzedCowbird => &BirdCardColor::Pink,
      Self::BrownPelican => &BirdCardColor::White,
      Self::BrownHeadedCowbird => &BirdCardColor::Pink,
      Self::BurrowingOwl => &BirdCardColor::Brown,
      Self::Bushtit => &BirdCardColor::Brown,
      Self::CaliforniaCondor => &BirdCardColor::White,
      Self::CaliforniaQuail => &BirdCardColor::Brown,
      Self::CanadaGoose => &BirdCardColor::Brown,
      Self::Canvasback => &BirdCardColor::Brown,
      Self::CarolinaChickadee => &BirdCardColor::Brown,
      Self::CarolinaWren => &BirdCardColor::White,
      Self::CassinsFinch => &BirdCardColor::White,
      Self::CassinsSparrow => &BirdCardColor::Brown,
      Self::CedarWaxwing => &BirdCardColor::Brown,
      Self::CeruleanWarbler => &BirdCardColor::White,
      Self::ChestnutCollaredLongspur => &BirdCardColor::White,
      Self::ChihuahuanRaven => &BirdCardColor::Brown,
      Self::ChimneySwift => &BirdCardColor::Brown,
      Self::ChippingSparrow => &BirdCardColor::Brown,
      Self::ClarksGrebe => &BirdCardColor::Brown,
      Self::ClarksNutcracker => &BirdCardColor::Brown,
      Self::CommonGrackle => &BirdCardColor::Brown,
      Self::CommonLoon => &BirdCardColor::Brown,
      Self::CommonMerganser => &BirdCardColor::Brown,
      Self::CommonNighthawk => &BirdCardColor::Brown,
      Self::CommonRaven => &BirdCardColor::Brown,
      Self::CommonYellowthroat => &BirdCardColor::Brown,
      Self::CoopersHawk => &BirdCardColor::Brown,
      Self::DarkEyedJunco => &BirdCardColor::Brown,
      Self::Dickcissel => &BirdCardColor::Brown,
      Self::DoubleCrestedCormorant => &BirdCardColor::Brown,
      Self::DownyWoodpecker => &BirdCardColor::White,
      Self::EasternBluebird => &BirdCardColor::White,
      Self::EasternKingbird => &BirdCardColor::Pink,
      Self::EasternPhoebe => &BirdCardColor::Brown,
      Self::EasternScreechOwl => &BirdCardColor::Brown,
      Self::FerruginousHawk => &BirdCardColor::Brown,
      Self::FishCrow => &BirdCardColor::Brown,
      Self::ForstersTern => &BirdCardColor::Brown,
      Self::FranklinsGull => &BirdCardColor::Brown,
      Self::GoldenEagle => &BirdCardColor::Brown,
      Self::GrasshopperSparrow => &BirdCardColor::Brown,
      Self::GrayCatbird => &BirdCardColor::Brown,
      Self::GreatBlueHeron => &BirdCardColor::White,
      Self::GreatCrestedFlycatcher => &BirdCardColor::Brown,
      Self::GreatEgret => &BirdCardColor::White,
      Self::GreatHornedOwl => &BirdCardColor::Brown,
      Self::GreaterPrairieChicken => &BirdCardColor::White,
      Self::GreaterRoadrunner => &BirdCardColor::Brown,
      Self::GreenHeron => &BirdCardColor::Brown,
      Self::HermitThrush => &BirdCardColor::Brown,
      Self::HoodedMerganser => &BirdCardColor::Brown,
      Self::HoodedWarbler => &BirdCardColor::None,
      Self::HornedLark => &BirdCardColor::Pink,
      Self::HouseFinch => &BirdCardColor::Brown,
      Self::HouseWren => &BirdCardColor::White,
      Self::IncaDove => &BirdCardColor::White,
      Self::IndigoBunting => &BirdCardColor::Brown,
      Self::JuniperTitmouse => &BirdCardColor::Brown,
      Self::Killdeer => &BirdCardColor::Brown,
      Self::KingRail => &BirdCardColor::White,
      Self::LazuliBunting => &BirdCardColor::Brown,
      Self::LincolnsSparrow => &BirdCardColor::Brown,
      Self::LoggerheadShrike => &BirdCardColor::Pink,
      Self::Mallard => &BirdCardColor::Brown,
      Self::MississippiKite => &BirdCardColor::Brown,
      Self::MountainBluebird => &BirdCardColor::White,
      Self::MountainChickadee => &BirdCardColor::Brown,
      Self::MourningDove => &BirdCardColor::Brown,
      Self::NorthernBobwhite => &BirdCardColor::Brown,
      Self::NorthernCardinal => &BirdCardColor::Brown,
      Self::NorthernFlicker => &BirdCardColor::White,
      Self::NorthernHarrier => &BirdCardColor::Brown,
      Self::NorthernMockingbird => &BirdCardColor::Brown,
      Self::NorthernShoveler => &BirdCardColor::Brown,
      Self::Osprey => &BirdCardColor::Brown,
      Self::PaintedBunting => &BirdCardColor::White,
      Self::PaintedWhitestart => &BirdCardColor::Brown,
      Self::PeregrineFalcon => &BirdCardColor::Brown,
      Self::PiedBilledGrebe => &BirdCardColor::Brown,
      Self::PileatedWoodpecker => &BirdCardColor::Brown,
      Self::PineSiskin => &BirdCardColor::Brown,
      Self::ProthonotaryWarbler => &BirdCardColor::None,
      Self::PurpleGallinule => &BirdCardColor::Brown,
      Self::PurpleMartin => &BirdCardColor::Brown,
      Self::PygmyNuthatch => &BirdCardColor::Brown,
      Self::RedCrossbill => &BirdCardColor::Brown,
      Self::RedBelliedWoodpecker => &BirdCardColor::Brown,
      Self::RedBreastedMerganser => &BirdCardColor::Brown,
      Self::RedBreastedNuthatch => &BirdCardColor::Brown,
      Self::RedCockadedWoodpecker => &BirdCardColor::White,
      Self::RedEyedVireo => &BirdCardColor::White,
      Self::RedHeadedWoodpecker => &BirdCardColor::Brown,
      Self::RedShoulderedHawk => &BirdCardColor::Brown,
      Self::RedTailedHawk => &BirdCardColor::Brown,
      Self::RedWingedBlackbird => &BirdCardColor::Brown,
      Self::RingBilledGull => &BirdCardColor::Brown,
      Self::RoseBreastedGrosbeak => &BirdCardColor::Brown,
      Self::RoseateSpoonbill => &BirdCardColor::White,
      Self::RubyCrownedKinglet => &BirdCardColor::White,
      Self::RubyThroatedHummingbird => &BirdCardColor::Brown,
      Self::RuddyDuck => &BirdCardColor::Brown,
      Self::SandhillCrane => &BirdCardColor::Brown,
      Self::SavannahSparrow => &BirdCardColor::White,
      Self::SaysPhoebe => &BirdCardColor::White,
      Self::ScaledQuail => &BirdCardColor::Brown,
      Self::ScissorTailedFlycatcher => &BirdCardColor::Brown,
      Self::SnowyEgret => &BirdCardColor::Brown,
      Self::SongSparrow => &BirdCardColor::Brown,
      Self::SpottedOwl => &BirdCardColor::White,
      Self::SpottedSandpiper => &BirdCardColor::Brown,
      Self::SpottedTowhee => &BirdCardColor::Brown,
      Self::SpraguesPipit => &BirdCardColor::White,
      Self::StellersJay => &BirdCardColor::Brown,
      Self::SwainsonsHawk => &BirdCardColor::Brown,
      Self::TreeSwallow => &BirdCardColor::Brown,
      Self::TrumpeterSwan => &BirdCardColor::None,
      Self::TuftedTitmouse => &BirdCardColor::White,
      Self::TurkeyVulture => &BirdCardColor::Pink,
      Self::VauxsSwift => &BirdCardColor::Brown,
      Self::VioletGreenSwallow => &BirdCardColor::Brown,
      Self::WesternMeadowlark => &BirdCardColor::Brown,
      Self::WesternTanager => &BirdCardColor::Brown,
      Self::WhiteBreastedNuthatch => &BirdCardColor::Brown,
      Self::WhiteCrownedSparrow => &BirdCardColor::Brown,
      Self::WhiteFacedIbis => &BirdCardColor::Brown,
      Self::WhiteThroatedSwift => &BirdCardColor::Brown,
      Self::WhoopingCrane => &BirdCardColor::White,
      Self::WildTurkey => &BirdCardColor::None,
      Self::Willet => &BirdCardColor::Brown,
      Self::WilsonsSnipe => &BirdCardColor::Brown,
      Self::WoodDuck => &BirdCardColor::Brown,
      Self::WoodStork => &BirdCardColor::White,
      Self::YellowBelliedSapsucker => &BirdCardColor::Brown,
      Self::YellowBilledCuckoo => &BirdCardColor::Pink,
      Self::YellowBreastedChat => &BirdCardColor::Brown,
      Self::YellowHeadedBlackbird => &BirdCardColor::Brown,
      Self::YellowRumpedWarbler => &BirdCardColor::Brown,
    }
  }

  pub fn points(&self) -> u8 {
    match self {
      Self::AcornWoodpecker => 5,
      Self::AmericanAvocet => 6,
      Self::AmericanBittern => 7,
      Self::AmericanCoot => 3,
      Self::AmericanCrow => 4,
      Self::AmericanGoldfinch => 3,
      Self::AmericanKestrel => 5,
      Self::AmericanOystercatcher => 5,
      Self::AmericanRedstart => 4,
      Self::AmericanRobin => 1,
      Self::AmericanWhitePelican => 5,
      Self::AmericanWoodcock => 9,
      Self::Anhinga => 6,
      Self::AnnasHummingbird => 4,
      Self::AshThroatedFlycatcher => 4,
      Self::AtlanticPuffin => 8,
      Self::BairdsSparrow => 3,
      Self::BaldEagle => 9,
      Self::BaltimoreOriole => 9,
      Self::BarnOwl => 5,
      Self::BarnSwallow => 1,
      Self::BarredOwl => 3,
      Self::BarrowsGoldeneye => 5,
      Self::BellsVireo => 4,
      Self::BeltedKingfisher => 4,
      Self::BewicksWren => 4,
      Self::BlackSkimmer => 6,
      Self::BlackTern => 4,
      Self::BlackVulture => 2,
      Self::BlackBelliedWhistlingDuck => 2,
      Self::BlackBilledMagpie => 3,
      Self::BlackChinnedHummingbird => 4,
      Self::BlackCrownedNightHeron => 9,
      Self::BlackNeckedStilt => 4,
      Self::BlueGrosbeak => 4,
      Self::BlueJay => 3,
      Self::BlueGrayGnatcatcher => 1,
      Self::BlueWingedWarbler => 8,
      Self::Bobolink => 4,
      Self::Brant => 3,
      Self::BrewersBlackbird => 3,
      Self::BroadWingedHawk => 4,
      Self::BronzedCowbird => 5,
      Self::BrownPelican => 4,
      Self::BrownHeadedCowbird => 3,
      Self::BurrowingOwl => 5,
      Self::Bushtit => 2,
      Self::CaliforniaCondor => 1,
      Self::CaliforniaQuail => 3,
      Self::CanadaGoose => 3,
      Self::Canvasback => 4,
      Self::CarolinaChickadee => 2,
      Self::CarolinaWren => 1,
      Self::CassinsFinch => 4,
      Self::CassinsSparrow => 3,
      Self::CedarWaxwing => 3,
      Self::CeruleanWarbler => 4,
      Self::ChestnutCollaredLongspur => 5,
      Self::ChihuahuanRaven => 4,
      Self::ChimneySwift => 3,
      Self::ChippingSparrow => 1,
      Self::ClarksGrebe => 5,
      Self::ClarksNutcracker => 5,
      Self::CommonGrackle => 3,
      Self::CommonLoon => 6,
      Self::CommonMerganser => 5,
      Self::CommonNighthawk => 3,
      Self::CommonRaven => 5,
      Self::CommonYellowthroat => 1,
      Self::CoopersHawk => 3,
      Self::DarkEyedJunco => 3,
      Self::Dickcissel => 4,
      Self::DoubleCrestedCormorant => 3,
      Self::DownyWoodpecker => 3,
      Self::EasternBluebird => 4,
      Self::EasternKingbird => 2,
      Self::EasternPhoebe => 3,
      Self::EasternScreechOwl => 4,
      Self::FerruginousHawk => 6,
      Self::FishCrow => 6,
      Self::ForstersTern => 4,
      Self::FranklinsGull => 3,
      Self::GoldenEagle => 8,
      Self::GrasshopperSparrow => 2,
      Self::GrayCatbird => 5,
      Self::GreatBlueHeron => 5,
      Self::GreatCrestedFlycatcher => 5,
      Self::GreatEgret => 7,
      Self::GreatHornedOwl => 8,
      Self::GreaterPrairieChicken => 5,
      Self::GreaterRoadrunner => 7,
      Self::GreenHeron => 4,
      Self::HermitThrush => 7,
      Self::HoodedMerganser => 5,
      Self::HoodedWarbler => 7,
      Self::HornedLark => 5,
      Self::HouseFinch => 3,
      Self::HouseWren => 1,
      Self::IncaDove => 2,
      Self::IndigoBunting => 5,
      Self::JuniperTitmouse => 4,
      Self::Killdeer => 1,
      Self::KingRail => 4,
      Self::LazuliBunting => 4,
      Self::LincolnsSparrow => 3,
      Self::LoggerheadShrike => 3,
      Self::Mallard => 0,
      Self::MississippiKite => 4,
      Self::MountainBluebird => 4,
      Self::MountainChickadee => 2,
      Self::MourningDove => 0,
      Self::NorthernBobwhite => 5,
      Self::NorthernCardinal => 3,
      Self::NorthernFlicker => 2,
      Self::NorthernHarrier => 3,
      Self::NorthernMockingbird => 2,
      Self::NorthernShoveler => 7,
      Self::Osprey => 5,
      Self::PaintedBunting => 5,
      Self::PaintedWhitestart => 1,
      Self::PeregrineFalcon => 5,
      Self::PiedBilledGrebe => 0,
      Self::PileatedWoodpecker => 4,
      Self::PineSiskin => 3,
      Self::ProthonotaryWarbler => 8,
      Self::PurpleGallinule => 7,
      Self::PurpleMartin => 2,
      Self::PygmyNuthatch => 2,
      Self::RedCrossbill => 6,
      Self::RedBelliedWoodpecker => 1,
      Self::RedBreastedMerganser => 3,
      Self::RedBreastedNuthatch => 2,
      Self::RedCockadedWoodpecker => 4,
      Self::RedEyedVireo => 3,
      Self::RedHeadedWoodpecker => 4,
      Self::RedShoulderedHawk => 3,
      Self::RedTailedHawk => 5,
      Self::RedWingedBlackbird => 2,
      Self::RingBilledGull => 4,
      Self::RoseBreastedGrosbeak => 6,
      Self::RoseateSpoonbill => 6,
      Self::RubyCrownedKinglet => 2,
      Self::RubyThroatedHummingbird => 4,
      Self::RuddyDuck => 0,
      Self::SandhillCrane => 5,
      Self::SavannahSparrow => 2,
      Self::SaysPhoebe => 5,
      Self::ScaledQuail => 0,
      Self::ScissorTailedFlycatcher => 8,
      Self::SnowyEgret => 4,
      Self::SongSparrow => 0,
      Self::SpottedOwl => 5,
      Self::SpottedSandpiper => 5,
      Self::SpottedTowhee => 0,
      Self::SpraguesPipit => 3,
      Self::StellersJay => 5,
      Self::SwainsonsHawk => 5,
      Self::TreeSwallow => 3,
      Self::TrumpeterSwan => 9,
      Self::TuftedTitmouse => 2,
      Self::TurkeyVulture => 1,
      Self::VauxsSwift => 2,
      Self::VioletGreenSwallow => 3,
      Self::WesternMeadowlark => 2,
      Self::WesternTanager => 6,
      Self::WhiteBreastedNuthatch => 2,
      Self::WhiteCrownedSparrow => 2,
      Self::WhiteFacedIbis => 8,
      Self::WhiteThroatedSwift => 2,
      Self::WhoopingCrane => 6,
      Self::WildTurkey => 8,
      Self::Willet => 4,
      Self::WilsonsSnipe => 5,
      Self::WoodDuck => 4,
      Self::WoodStork => 6,
      Self::YellowBelliedSapsucker => 3,
      Self::YellowBilledCuckoo => 5,
      Self::YellowBreastedChat => 5,
      Self::YellowHeadedBlackbird => 4,
      Self::YellowRumpedWarbler => 1,
    }
  }

  pub fn habitats(&self) -> &'static [Habitat] {
    match self {
      Self::AcornWoodpecker => &[Habitat::Forest],
      Self::AmericanAvocet => &[Habitat::Wetland],
      Self::AmericanBittern => &[Habitat::Wetland],
      Self::AmericanCoot => &[Habitat::Wetland],
      Self::AmericanCrow => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::AmericanGoldfinch => &[Habitat::Grassland],
      Self::AmericanKestrel => &[Habitat::Grassland],
      Self::AmericanOystercatcher => &[Habitat::Wetland],
      Self::AmericanRedstart => &[Habitat::Forest],
      Self::AmericanRobin => &[Habitat::Forest, Habitat::Grassland],
      Self::AmericanWhitePelican => &[Habitat::Wetland],
      Self::AmericanWoodcock => &[Habitat::Forest, Habitat::Grassland],
      Self::Anhinga => &[Habitat::Wetland],
      Self::AnnasHummingbird => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::AshThroatedFlycatcher => &[Habitat::Grassland],
      Self::AtlanticPuffin => &[Habitat::Wetland],
      Self::BairdsSparrow => &[Habitat::Grassland],
      Self::BaldEagle => &[Habitat::Wetland],
      Self::BaltimoreOriole => &[Habitat::Forest],
      Self::BarnOwl => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::BarnSwallow => &[Habitat::Grassland, Habitat::Wetland],
      Self::BarredOwl => &[Habitat::Forest],
      Self::BarrowsGoldeneye => &[Habitat::Wetland],
      Self::BellsVireo => &[Habitat::Forest, Habitat::Grassland],
      Self::BeltedKingfisher => &[Habitat::Wetland],
      Self::BewicksWren => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::BlackSkimmer => &[Habitat::Wetland],
      Self::BlackTern => &[Habitat::Wetland],
      Self::BlackVulture => &[Habitat::Forest],
      Self::BlackBelliedWhistlingDuck => &[Habitat::Wetland],
      Self::BlackBilledMagpie => &[Habitat::Grassland],
      Self::BlackChinnedHummingbird => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::BlackCrownedNightHeron => &[Habitat::Wetland],
      Self::BlackNeckedStilt => &[Habitat::Wetland],
      Self::BlueGrosbeak => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::BlueJay => &[Habitat::Forest],
      Self::BlueGrayGnatcatcher => &[Habitat::Forest],
      Self::BlueWingedWarbler => &[Habitat::Forest, Habitat::Grassland],
      Self::Bobolink => &[Habitat::Grassland],
      Self::Brant => &[Habitat::Wetland],
      Self::BrewersBlackbird => &[Habitat::Grassland],
      Self::BroadWingedHawk => &[Habitat::Forest],
      Self::BronzedCowbird => &[Habitat::Grassland],
      Self::BrownPelican => &[Habitat::Wetland],
      Self::BrownHeadedCowbird => &[Habitat::Grassland],
      Self::BurrowingOwl => &[Habitat::Grassland],
      Self::Bushtit => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::CaliforniaCondor => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::CaliforniaQuail => &[Habitat::Forest, Habitat::Grassland],
      Self::CanadaGoose => &[Habitat::Grassland, Habitat::Wetland],
      Self::Canvasback => &[Habitat::Wetland],
      Self::CarolinaChickadee => &[Habitat::Forest],
      Self::CarolinaWren => &[Habitat::Forest],
      Self::CassinsFinch => &[Habitat::Forest],
      Self::CassinsSparrow => &[Habitat::Grassland],
      Self::CedarWaxwing => &[Habitat::Forest, Habitat::Grassland],
      Self::CeruleanWarbler => &[Habitat::Forest],
      Self::ChestnutCollaredLongspur => &[Habitat::Grassland],
      Self::ChihuahuanRaven => &[Habitat::Grassland],
      Self::ChimneySwift => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::ChippingSparrow => &[Habitat::Forest, Habitat::Grassland],
      Self::ClarksGrebe => &[Habitat::Wetland],
      Self::ClarksNutcracker => &[Habitat::Forest],
      Self::CommonGrackle => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::CommonLoon => &[Habitat::Wetland],
      Self::CommonMerganser => &[Habitat::Wetland],
      Self::CommonNighthawk => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::CommonRaven => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::CommonYellowthroat => &[Habitat::Wetland],
      Self::CoopersHawk => &[Habitat::Forest],
      Self::DarkEyedJunco => &[Habitat::Forest, Habitat::Grassland],
      Self::Dickcissel => &[Habitat::Grassland],
      Self::DoubleCrestedCormorant => &[Habitat::Wetland],
      Self::DownyWoodpecker => &[Habitat::Forest],
      Self::EasternBluebird => &[Habitat::Grassland],
      Self::EasternKingbird => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::EasternPhoebe => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::EasternScreechOwl => &[Habitat::Forest],
      Self::FerruginousHawk => &[Habitat::Grassland],
      Self::FishCrow => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::ForstersTern => &[Habitat::Wetland],
      Self::FranklinsGull => &[Habitat::Grassland, Habitat::Wetland],
      Self::GoldenEagle => &[Habitat::Grassland, Habitat::Wetland],
      Self::GrasshopperSparrow => &[Habitat::Grassland],
      Self::GrayCatbird => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::GreatBlueHeron => &[Habitat::Wetland],
      Self::GreatCrestedFlycatcher => &[Habitat::Forest],
      Self::GreatEgret => &[Habitat::Wetland],
      Self::GreatHornedOwl => &[Habitat::Forest],
      Self::GreaterPrairieChicken => &[Habitat::Grassland],
      Self::GreaterRoadrunner => &[Habitat::Grassland],
      Self::GreenHeron => &[Habitat::Wetland],
      Self::HermitThrush => &[Habitat::Forest],
      Self::HoodedMerganser => &[Habitat::Wetland],
      Self::HoodedWarbler => &[Habitat::Forest],
      Self::HornedLark => &[Habitat::Grassland],
      Self::HouseFinch => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::HouseWren => &[Habitat::Forest, Habitat::Grassland],
      Self::IncaDove => &[Habitat::Grassland],
      Self::IndigoBunting => &[Habitat::Forest, Habitat::Grassland],
      Self::JuniperTitmouse => &[Habitat::Forest],
      Self::Killdeer => &[Habitat::Grassland, Habitat::Wetland],
      Self::KingRail => &[Habitat::Wetland],
      Self::LazuliBunting => &[Habitat::Grassland],
      Self::LincolnsSparrow => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::LoggerheadShrike => &[Habitat::Grassland, Habitat::Wetland],
      Self::Mallard => &[Habitat::Wetland],
      Self::MississippiKite => &[Habitat::Forest, Habitat::Grassland],
      Self::MountainBluebird => &[Habitat::Grassland],
      Self::MountainChickadee => &[Habitat::Forest],
      Self::MourningDove => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::NorthernBobwhite => &[Habitat::Grassland],
      Self::NorthernCardinal => &[Habitat::Forest],
      Self::NorthernFlicker => &[Habitat::Forest, Habitat::Grassland],
      Self::NorthernHarrier => &[Habitat::Grassland, Habitat::Wetland],
      Self::NorthernMockingbird => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::NorthernShoveler => &[Habitat::Wetland],
      Self::Osprey => &[Habitat::Wetland],
      Self::PaintedBunting => &[Habitat::Grassland],
      Self::PaintedWhitestart => &[Habitat::Forest],
      Self::PeregrineFalcon => &[Habitat::Grassland, Habitat::Wetland],
      Self::PiedBilledGrebe => &[Habitat::Wetland],
      Self::PileatedWoodpecker => &[Habitat::Forest],
      Self::PineSiskin => &[Habitat::Forest],
      Self::ProthonotaryWarbler => &[Habitat::Forest, Habitat::Wetland],
      Self::PurpleGallinule => &[Habitat::Wetland],
      Self::PurpleMartin => &[Habitat::Grassland, Habitat::Wetland],
      Self::PygmyNuthatch => &[Habitat::Forest],
      Self::RedCrossbill => &[Habitat::Forest],
      Self::RedBelliedWoodpecker => &[Habitat::Forest],
      Self::RedBreastedMerganser => &[Habitat::Wetland],
      Self::RedBreastedNuthatch => &[Habitat::Forest],
      Self::RedCockadedWoodpecker => &[Habitat::Forest],
      Self::RedEyedVireo => &[Habitat::Forest],
      Self::RedHeadedWoodpecker => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::RedShoulderedHawk => &[Habitat::Forest],
      Self::RedTailedHawk => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::RedWingedBlackbird => &[Habitat::Grassland, Habitat::Wetland],
      Self::RingBilledGull => &[Habitat::Wetland],
      Self::RoseBreastedGrosbeak => &[Habitat::Forest],
      Self::RoseateSpoonbill => &[Habitat::Wetland],
      Self::RubyCrownedKinglet => &[Habitat::Forest],
      Self::RubyThroatedHummingbird => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::RuddyDuck => &[Habitat::Wetland],
      Self::SandhillCrane => &[Habitat::Grassland, Habitat::Wetland],
      Self::SavannahSparrow => &[Habitat::Grassland],
      Self::SaysPhoebe => &[Habitat::Grassland],
      Self::ScaledQuail => &[Habitat::Grassland],
      Self::ScissorTailedFlycatcher => &[Habitat::Grassland],
      Self::SnowyEgret => &[Habitat::Wetland],
      Self::SongSparrow => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::SpottedOwl => &[Habitat::Forest],
      Self::SpottedSandpiper => &[Habitat::Wetland],
      Self::SpottedTowhee => &[Habitat::Forest, Habitat::Grassland],
      Self::SpraguesPipit => &[Habitat::Grassland],
      Self::StellersJay => &[Habitat::Forest],
      Self::SwainsonsHawk => &[Habitat::Grassland],
      Self::TreeSwallow => &[Habitat::Wetland],
      Self::TrumpeterSwan => &[Habitat::Wetland],
      Self::TuftedTitmouse => &[Habitat::Forest],
      Self::TurkeyVulture => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::VauxsSwift => &[Habitat::Forest],
      Self::VioletGreenSwallow => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::WesternMeadowlark => &[Habitat::Grassland],
      Self::WesternTanager => &[Habitat::Forest],
      Self::WhiteBreastedNuthatch => &[Habitat::Forest],
      Self::WhiteCrownedSparrow => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::WhiteFacedIbis => &[Habitat::Wetland],
      Self::WhiteThroatedSwift => &[Habitat::Grassland],
      Self::WhoopingCrane => &[Habitat::Wetland],
      Self::WildTurkey => &[Habitat::Forest, Habitat::Grassland],
      Self::Willet => &[Habitat::Wetland],
      Self::WilsonsSnipe => &[Habitat::Wetland],
      Self::WoodDuck => &[Habitat::Forest, Habitat::Wetland],
      Self::WoodStork => &[Habitat::Wetland],
      Self::YellowBelliedSapsucker => &[Habitat::Forest],
      Self::YellowBilledCuckoo => &[Habitat::Forest],
      Self::YellowBreastedChat => &[Habitat::Forest, Habitat::Grassland, Habitat::Wetland],
      Self::YellowHeadedBlackbird => &[Habitat::Wetland],
      Self::YellowRumpedWarbler => &[Habitat::Forest],
    }
  }

  pub fn wingspan(&self) -> Option<u16> {
    match self {
      Self::AcornWoodpecker => Some(46),
      Self::AmericanAvocet => Some(79),
      Self::AmericanBittern => Some(107),
      Self::AmericanCoot => Some(61),
      Self::AmericanCrow => Some(99),
      Self::AmericanGoldfinch => Some(23),
      Self::AmericanKestrel => Some(56),
      Self::AmericanOystercatcher => Some(81),
      Self::AmericanRedstart => Some(20),
      Self::AmericanRobin => Some(43),
      Self::AmericanWhitePelican => Some(274),
      Self::AmericanWoodcock => Some(46),
      Self::Anhinga => Some(114),
      Self::AnnasHummingbird => Some(13),
      Self::AshThroatedFlycatcher => Some(30),
      Self::AtlanticPuffin => Some(53),
      Self::BairdsSparrow => Some(23),
      Self::BaldEagle => Some(203),
      Self::BaltimoreOriole => Some(30),
      Self::BarnOwl => Some(107),
      Self::BarnSwallow => Some(38),
      Self::BarredOwl => Some(107),
      Self::BarrowsGoldeneye => Some(71),
      Self::BellsVireo => Some(18),
      Self::BeltedKingfisher => Some(53),
      Self::BewicksWren => Some(18),
      Self::BlackSkimmer => Some(112),
      Self::BlackTern => Some(61),
      Self::BlackVulture => Some(150),
      Self::BlackBelliedWhistlingDuck => Some(76),
      Self::BlackBilledMagpie => Some(64),
      Self::BlackChinnedHummingbird => Some(8),
      Self::BlackCrownedNightHeron => Some(112),
      Self::BlackNeckedStilt => Some(74),
      Self::BlueGrosbeak => Some(28),
      Self::BlueJay => Some(41),
      Self::BlueGrayGnatcatcher => Some(15),
      Self::BlueWingedWarbler => Some(20),
      Self::Bobolink => Some(30),
      Self::Brant => Some(114),
      Self::BrewersBlackbird => Some(41),
      Self::BroadWingedHawk => Some(85),
      Self::BronzedCowbird => Some(36),
      Self::BrownPelican => Some(201),
      Self::BrownHeadedCowbird => Some(30),
      Self::BurrowingOwl => Some(53),
      Self::Bushtit => Some(15),
      Self::CaliforniaCondor => Some(277),
      Self::CaliforniaQuail => Some(36),
      Self::CanadaGoose => Some(132),
      Self::Canvasback => Some(82),
      Self::CarolinaChickadee => Some(20),
      Self::CarolinaWren => Some(20),
      Self::CassinsFinch => Some(30),
      Self::CassinsSparrow => Some(20),
      Self::CedarWaxwing => Some(25),
      Self::CeruleanWarbler => Some(20),
      Self::ChestnutCollaredLongspur => Some(25),
      Self::ChihuahuanRaven => Some(112),
      Self::ChimneySwift => Some(36),
      Self::ChippingSparrow => Some(23),
      Self::ClarksGrebe => Some(61),
      Self::ClarksNutcracker => Some(61),
      Self::CommonGrackle => Some(43),
      Self::CommonLoon => Some(117),
      Self::CommonMerganser => Some(86),
      Self::CommonNighthawk => Some(56),
      Self::CommonRaven => Some(135),
      Self::CommonYellowthroat => Some(18),
      Self::CoopersHawk => Some(79),
      Self::DarkEyedJunco => Some(23),
      Self::Dickcissel => Some(25),
      Self::DoubleCrestedCormorant => Some(132),
      Self::DownyWoodpecker => Some(30),
      Self::EasternBluebird => Some(33),
      Self::EasternKingbird => Some(38),
      Self::EasternPhoebe => Some(28),
      Self::EasternScreechOwl => Some(51),
      Self::FerruginousHawk => Some(142),
      Self::FishCrow => Some(91),
      Self::ForstersTern => Some(79),
      Self::FranklinsGull => Some(91),
      Self::GoldenEagle => Some(201),
      Self::GrasshopperSparrow => Some(20),
      Self::GrayCatbird => Some(28),
      Self::GreatBlueHeron => Some(183),
      Self::GreatCrestedFlycatcher => Some(33),
      Self::GreatEgret => Some(130),
      Self::GreatHornedOwl => Some(112),
      Self::GreaterPrairieChicken => Some(71),
      Self::GreaterRoadrunner => Some(56),
      Self::GreenHeron => Some(66),
      Self::HermitThrush => Some(30),
      Self::HoodedMerganser => Some(61),
      Self::HoodedWarbler => Some(18),
      Self::HornedLark => Some(30),
      Self::HouseFinch => Some(25),
      Self::HouseWren => Some(15),
      Self::IncaDove => Some(28),
      Self::IndigoBunting => Some(20),
      Self::JuniperTitmouse => Some(23),
      Self::Killdeer => Some(46),
      Self::KingRail => Some(51),
      Self::LazuliBunting => Some(23),
      Self::LincolnsSparrow => Some(20),
      Self::LoggerheadShrike => Some(30),
      Self::Mallard => Some(89),
      Self::MississippiKite => Some(79),
      Self::MountainBluebird => Some(36),
      Self::MountainChickadee => Some(23),
      Self::MourningDove => Some(46),
      Self::NorthernBobwhite => Some(33),
      Self::NorthernCardinal => Some(30),
      Self::NorthernFlicker => Some(51),
      Self::NorthernHarrier => Some(109),
      Self::NorthernMockingbird => Some(36),
      Self::NorthernShoveler => Some(76),
      Self::Osprey => Some(160),
      Self::PaintedBunting => Some(23),
      Self::PaintedWhitestart => Some(22),
      Self::PeregrineFalcon => Some(104),
      Self::PiedBilledGrebe => Some(41),
      Self::PileatedWoodpecker => Some(74),
      Self::PineSiskin => Some(23),
      Self::ProthonotaryWarbler => Some(23),
      Self::PurpleGallinule => Some(56),
      Self::PurpleMartin => Some(46),
      Self::PygmyNuthatch => Some(20),
      Self::RedCrossbill => Some(28),
      Self::RedBelliedWoodpecker => Some(41),
      Self::RedBreastedMerganser => Some(78),
      Self::RedBreastedNuthatch => Some(23),
      Self::RedCockadedWoodpecker => Some(36),
      Self::RedEyedVireo => Some(25),
      Self::RedHeadedWoodpecker => Some(43),
      Self::RedShoulderedHawk => Some(102),
      Self::RedTailedHawk => Some(124),
      Self::RedWingedBlackbird => Some(33),
      Self::RingBilledGull => Some(122),
      Self::RoseBreastedGrosbeak => Some(33),
      Self::RoseateSpoonbill => Some(127),
      Self::RubyCrownedKinglet => Some(20),
      Self::RubyThroatedHummingbird => Some(10),
      Self::RuddyDuck => Some(48),
      Self::SandhillCrane => Some(196),
      Self::SavannahSparrow => Some(18),
      Self::SaysPhoebe => Some(33),
      Self::ScaledQuail => Some(36),
      Self::ScissorTailedFlycatcher => Some(38),
      Self::SnowyEgret => Some(104),
      Self::SongSparrow => Some(20),
      Self::SpottedOwl => Some(102),
      Self::SpottedSandpiper => Some(38),
      Self::SpottedTowhee => Some(28),
      Self::SpraguesPipit => Some(25),
      Self::StellersJay => Some(48),
      Self::SwainsonsHawk => Some(130),
      Self::TreeSwallow => Some(38),
      Self::TrumpeterSwan => Some(203),
      Self::TuftedTitmouse => Some(25),
      Self::TurkeyVulture => Some(170),
      Self::VauxsSwift => Some(31),
      Self::VioletGreenSwallow => Some(36),
      Self::WesternMeadowlark => Some(38),
      Self::WesternTanager => Some(30),
      Self::WhiteBreastedNuthatch => Some(28),
      Self::WhiteCrownedSparrow => Some(25),
      Self::WhiteFacedIbis => Some(91),
      Self::WhiteThroatedSwift => Some(38),
      Self::WhoopingCrane => Some(221),
      Self::WildTurkey => Some(135),
      Self::Willet => Some(66),
      Self::WilsonsSnipe => Some(41),
      Self::WoodDuck => Some(76),
      Self::WoodStork => Some(155),
      Self::YellowBelliedSapsucker => Some(41),
      Self::YellowBilledCuckoo => Some(46),
      Self::YellowBreastedChat => Some(25),
      Self::YellowHeadedBlackbird => Some(38),
      Self::YellowRumpedWarbler => Some(23),
    }
  }

  pub fn egg_capacity(&self) -> u8 {
    match self {
      Self::AcornWoodpecker => 4,
      Self::AmericanAvocet => 2,
      Self::AmericanBittern => 2,
      Self::AmericanCoot => 5,
      Self::AmericanCrow => 2,
      Self::AmericanGoldfinch => 3,
      Self::AmericanKestrel => 3,
      Self::AmericanOystercatcher => 2,
      Self::AmericanRedstart => 2,
      Self::AmericanRobin => 4,
      Self::AmericanWhitePelican => 1,
      Self::AmericanWoodcock => 2,
      Self::Anhinga => 2,
      Self::AnnasHummingbird => 2,
      Self::AshThroatedFlycatcher => 4,
      Self::AtlanticPuffin => 1,
      Self::BairdsSparrow => 2,
      Self::BaldEagle => 1,
      Self::BaltimoreOriole => 2,
      Self::BarnOwl => 4,
      Self::BarnSwallow => 3,
      Self::BarredOwl => 2,
      Self::BarrowsGoldeneye => 4,
      Self::BellsVireo => 2,
      Self::BeltedKingfisher => 4,
      Self::BewicksWren => 3,
      Self::BlackSkimmer => 2,
      Self::BlackTern => 2,
      Self::BlackVulture => 1,
      Self::BlackBelliedWhistlingDuck => 5,
      Self::BlackBilledMagpie => 3,
      Self::BlackChinnedHummingbird => 2,
      Self::BlackCrownedNightHeron => 2,
      Self::BlackNeckedStilt => 2,
      Self::BlueGrosbeak => 3,
      Self::BlueJay => 2,
      Self::BlueGrayGnatcatcher => 3,
      Self::BlueWingedWarbler => 2,
      Self::Bobolink => 3,
      Self::Brant => 2,
      Self::BrewersBlackbird => 3,
      Self::BroadWingedHawk => 2,
      Self::BronzedCowbird => 0,
      Self::BrownPelican => 2,
      Self::BrownHeadedCowbird => 0,
      Self::BurrowingOwl => 4,
      Self::Bushtit => 5,
      Self::CaliforniaCondor => 1,
      Self::CaliforniaQuail => 6,
      Self::CanadaGoose => 3,
      Self::Canvasback => 4,
      Self::CarolinaChickadee => 3,
      Self::CarolinaWren => 5,
      Self::CassinsFinch => 3,
      Self::CassinsSparrow => 2,
      Self::CedarWaxwing => 3,
      Self::CeruleanWarbler => 2,
      Self::ChestnutCollaredLongspur => 4,
      Self::ChihuahuanRaven => 3,
      Self::ChimneySwift => 2,
      Self::ChippingSparrow => 3,
      Self::ClarksGrebe => 2,
      Self::ClarksNutcracker => 2,
      Self::CommonGrackle => 3,
      Self::CommonLoon => 1,
      Self::CommonMerganser => 4,
      Self::CommonNighthawk => 2,
      Self::CommonRaven => 2,
      Self::CommonYellowthroat => 4,
      Self::CoopersHawk => 2,
      Self::DarkEyedJunco => 3,
      Self::Dickcissel => 3,
      Self::DoubleCrestedCormorant => 3,
      Self::DownyWoodpecker => 2,
      Self::EasternBluebird => 5,
      Self::EasternKingbird => 2,
      Self::EasternPhoebe => 4,
      Self::EasternScreechOwl => 2,
      Self::FerruginousHawk => 2,
      Self::FishCrow => 2,
      Self::ForstersTern => 2,
      Self::FranklinsGull => 2,
      Self::GoldenEagle => 1,
      Self::GrasshopperSparrow => 2,
      Self::GrayCatbird => 3,
      Self::GreatBlueHeron => 2,
      Self::GreatCrestedFlycatcher => 3,
      Self::GreatEgret => 3,
      Self::GreatHornedOwl => 2,
      Self::GreaterPrairieChicken => 4,
      Self::GreaterRoadrunner => 2,
      Self::GreenHeron => 3,
      Self::HermitThrush => 2,
      Self::HoodedMerganser => 4,
      Self::HoodedWarbler => 3,
      Self::HornedLark => 4,
      Self::HouseFinch => 6,
      Self::HouseWren => 5,
      Self::IncaDove => 4,
      Self::IndigoBunting => 3,
      Self::JuniperTitmouse => 3,
      Self::Killdeer => 3,
      Self::KingRail => 6,
      Self::LazuliBunting => 4,
      Self::LincolnsSparrow => 2,
      Self::LoggerheadShrike => 4,
      Self::Mallard => 4,
      Self::MississippiKite => 1,
      Self::MountainBluebird => 5,
      Self::MountainChickadee => 3,
      Self::MourningDove => 5,
      Self::NorthernBobwhite => 6,
      Self::NorthernCardinal => 5,
      Self::NorthernFlicker => 4,
      Self::NorthernHarrier => 2,
      Self::NorthernMockingbird => 4,
      Self::NorthernShoveler => 4,
      Self::Osprey => 2,
      Self::PaintedBunting => 4,
      Self::PaintedWhitestart => 3,
      Self::PeregrineFalcon => 2,
      Self::PiedBilledGrebe => 4,
      Self::PileatedWoodpecker => 2,
      Self::PineSiskin => 2,
      Self::ProthonotaryWarbler => 4,
      Self::PurpleGallinule => 4,
      Self::PurpleMartin => 3,
      Self::PygmyNuthatch => 4,
      Self::RedCrossbill => 2,
      Self::RedBelliedWoodpecker => 3,
      Self::RedBreastedMerganser => 4,
      Self::RedBreastedNuthatch => 3,
      Self::RedCockadedWoodpecker => 2,
      Self::RedEyedVireo => 2,
      Self::RedHeadedWoodpecker => 3,
      Self::RedShoulderedHawk => 2,
      Self::RedTailedHawk => 2,
      Self::RedWingedBlackbird => 3,
      Self::RingBilledGull => 2,
      Self::RoseBreastedGrosbeak => 3,
      Self::RoseateSpoonbill => 2,
      Self::RubyCrownedKinglet => 3,
      Self::RubyThroatedHummingbird => 2,
      Self::RuddyDuck => 5,
      Self::SandhillCrane => 1,
      Self::SavannahSparrow => 3,
      Self::SaysPhoebe => 3,
      Self::ScaledQuail => 6,
      Self::ScissorTailedFlycatcher => 2,
      Self::SnowyEgret => 2,
      Self::SongSparrow => 5,
      Self::SpottedOwl => 1,
      Self::SpottedSandpiper => 2,
      Self::SpottedTowhee => 4,
      Self::SpraguesPipit => 3,
      Self::StellersJay => 2,
      Self::SwainsonsHawk => 2,
      Self::TreeSwallow => 4,
      Self::TrumpeterSwan => 2,
      Self::TuftedTitmouse => 3,
      Self::TurkeyVulture => 1,
      Self::VauxsSwift => 3,
      Self::VioletGreenSwallow => 3,
      Self::WesternMeadowlark => 4,
      Self::WesternTanager => 2,
      Self::WhiteBreastedNuthatch => 3,
      Self::WhiteCrownedSparrow => 5,
      Self::WhiteFacedIbis => 2,
      Self::WhiteThroatedSwift => 2,
      Self::WhoopingCrane => 1,
      Self::WildTurkey => 5,
      Self::Willet => 2,
      Self::WilsonsSnipe => 2,
      Self::WoodDuck => 4,
      Self::WoodStork => 2,
      Self::YellowBelliedSapsucker => 3,
      Self::YellowBilledCuckoo => 2,
      Self::YellowBreastedChat => 3,
      Self::YellowHeadedBlackbird => 3,
      Self::YellowRumpedWarbler => 4,
    }
  }

  pub fn nest_type(&self) -> &NestType {
    match self {
      Self::AcornWoodpecker => &NestType::Cavity,
      Self::AmericanAvocet => &NestType::Ground,
      Self::AmericanBittern => &NestType::Platform,
      Self::AmericanCoot => &NestType::Platform,
      Self::AmericanCrow => &NestType::Platform,
      Self::AmericanGoldfinch => &NestType::Bowl,
      Self::AmericanKestrel => &NestType::Cavity,
      Self::AmericanOystercatcher => &NestType::Ground,
      Self::AmericanRedstart => &NestType::Bowl,
      Self::AmericanRobin => &NestType::Bowl,
      Self::AmericanWhitePelican => &NestType::Ground,
      Self::AmericanWoodcock => &NestType::Ground,
      Self::Anhinga => &NestType::Platform,
      Self::AnnasHummingbird => &NestType::Bowl,
      Self::AshThroatedFlycatcher => &NestType::Cavity,
      Self::AtlanticPuffin => &NestType::Wild,
      Self::BairdsSparrow => &NestType::Ground,
      Self::BaldEagle => &NestType::Platform,
      Self::BaltimoreOriole => &NestType::Wild,
      Self::BarnOwl => &NestType::Cavity,
      Self::BarnSwallow => &NestType::Wild,
      Self::BarredOwl => &NestType::Cavity,
      Self::BarrowsGoldeneye => &NestType::Cavity,
      Self::BellsVireo => &NestType::Wild,
      Self::BeltedKingfisher => &NestType::Wild,
      Self::BewicksWren => &NestType::Cavity,
      Self::BlackSkimmer => &NestType::Ground,
      Self::BlackTern => &NestType::Wild,
      Self::BlackVulture => &NestType::Cavity,
      Self::BlackBelliedWhistlingDuck => &NestType::Cavity,
      Self::BlackBilledMagpie => &NestType::Wild,
      Self::BlackChinnedHummingbird => &NestType::Bowl,
      Self::BlackCrownedNightHeron => &NestType::Platform,
      Self::BlackNeckedStilt => &NestType::Ground,
      Self::BlueGrosbeak => &NestType::Bowl,
      Self::BlueJay => &NestType::Bowl,
      Self::BlueGrayGnatcatcher => &NestType::Bowl,
      Self::BlueWingedWarbler => &NestType::Bowl,
      Self::Bobolink => &NestType::Ground,
      Self::Brant => &NestType::Ground,
      Self::BrewersBlackbird => &NestType::Bowl,
      Self::BroadWingedHawk => &NestType::Platform,
      Self::BronzedCowbird => &NestType::None,
      Self::BrownPelican => &NestType::Platform,
      Self::BrownHeadedCowbird => &NestType::None,
      Self::BurrowingOwl => &NestType::Wild,
      Self::Bushtit => &NestType::Wild,
      Self::CaliforniaCondor => &NestType::Ground,
      Self::CaliforniaQuail => &NestType::Ground,
      Self::CanadaGoose => &NestType::Ground,
      Self::Canvasback => &NestType::Wild,
      Self::CarolinaChickadee => &NestType::Cavity,
      Self::CarolinaWren => &NestType::Cavity,
      Self::CassinsFinch => &NestType::Bowl,
      Self::CassinsSparrow => &NestType::Ground,
      Self::CedarWaxwing => &NestType::Bowl,
      Self::CeruleanWarbler => &NestType::Bowl,
      Self::ChestnutCollaredLongspur => &NestType::Ground,
      Self::ChihuahuanRaven => &NestType::Platform,
      Self::ChimneySwift => &NestType::Wild,
      Self::ChippingSparrow => &NestType::Bowl,
      Self::ClarksGrebe => &NestType::Wild,
      Self::ClarksNutcracker => &NestType::Platform,
      Self::CommonGrackle => &NestType::Bowl,
      Self::CommonLoon => &NestType::Ground,
      Self::CommonMerganser => &NestType::Cavity,
      Self::CommonNighthawk => &NestType::Ground,
      Self::CommonRaven => &NestType::Platform,
      Self::CommonYellowthroat => &NestType::Bowl,
      Self::CoopersHawk => &NestType::Platform,
      Self::DarkEyedJunco => &NestType::Ground,
      Self::Dickcissel => &NestType::Ground,
      Self::DoubleCrestedCormorant => &NestType::Platform,
      Self::DownyWoodpecker => &NestType::Cavity,
      Self::EasternBluebird => &NestType::Cavity,
      Self::EasternKingbird => &NestType::Bowl,
      Self::EasternPhoebe => &NestType::Wild,
      Self::EasternScreechOwl => &NestType::Cavity,
      Self::FerruginousHawk => &NestType::Platform,
      Self::FishCrow => &NestType::Platform,
      Self::ForstersTern => &NestType::Wild,
      Self::FranklinsGull => &NestType::Wild,
      Self::GoldenEagle => &NestType::Platform,
      Self::GrasshopperSparrow => &NestType::Ground,
      Self::GrayCatbird => &NestType::Bowl,
      Self::GreatBlueHeron => &NestType::Platform,
      Self::GreatCrestedFlycatcher => &NestType::Cavity,
      Self::GreatEgret => &NestType::Platform,
      Self::GreatHornedOwl => &NestType::Platform,
      Self::GreaterPrairieChicken => &NestType::Ground,
      Self::GreaterRoadrunner => &NestType::Platform,
      Self::GreenHeron => &NestType::Platform,
      Self::HermitThrush => &NestType::Wild,
      Self::HoodedMerganser => &NestType::Cavity,
      Self::HoodedWarbler => &NestType::Bowl,
      Self::HornedLark => &NestType::Ground,
      Self::HouseFinch => &NestType::Bowl,
      Self::HouseWren => &NestType::Cavity,
      Self::IncaDove => &NestType::Platform,
      Self::IndigoBunting => &NestType::Bowl,
      Self::JuniperTitmouse => &NestType::Cavity,
      Self::Killdeer => &NestType::Ground,
      Self::KingRail => &NestType::Platform,
      Self::LazuliBunting => &NestType::Bowl,
      Self::LincolnsSparrow => &NestType::Ground,
      Self::LoggerheadShrike => &NestType::Bowl,
      Self::Mallard => &NestType::Ground,
      Self::MississippiKite => &NestType::Platform,
      Self::MountainBluebird => &NestType::Cavity,
      Self::MountainChickadee => &NestType::Cavity,
      Self::MourningDove => &NestType::Platform,
      Self::NorthernBobwhite => &NestType::Ground,
      Self::NorthernCardinal => &NestType::Bowl,
      Self::NorthernFlicker => &NestType::Cavity,
      Self::NorthernHarrier => &NestType::Platform,
      Self::NorthernMockingbird => &NestType::Bowl,
      Self::NorthernShoveler => &NestType::Ground,
      Self::Osprey => &NestType::Platform,
      Self::PaintedBunting => &NestType::Bowl,
      Self::PaintedWhitestart => &NestType::Ground,
      Self::PeregrineFalcon => &NestType::Platform,
      Self::PiedBilledGrebe => &NestType::Platform,
      Self::PileatedWoodpecker => &NestType::Cavity,
      Self::PineSiskin => &NestType::Bowl,
      Self::ProthonotaryWarbler => &NestType::Cavity,
      Self::PurpleGallinule => &NestType::Platform,
      Self::PurpleMartin => &NestType::Cavity,
      Self::PygmyNuthatch => &NestType::Cavity,
      Self::RedCrossbill => &NestType::Bowl,
      Self::RedBelliedWoodpecker => &NestType::Cavity,
      Self::RedBreastedMerganser => &NestType::Ground,
      Self::RedBreastedNuthatch => &NestType::Cavity,
      Self::RedCockadedWoodpecker => &NestType::Cavity,
      Self::RedEyedVireo => &NestType::Wild,
      Self::RedHeadedWoodpecker => &NestType::Cavity,
      Self::RedShoulderedHawk => &NestType::Platform,
      Self::RedTailedHawk => &NestType::Platform,
      Self::RedWingedBlackbird => &NestType::Bowl,
      Self::RingBilledGull => &NestType::Ground,
      Self::RoseBreastedGrosbeak => &NestType::Bowl,
      Self::RoseateSpoonbill => &NestType::Platform,
      Self::RubyCrownedKinglet => &NestType::Bowl,
      Self::RubyThroatedHummingbird => &NestType::Bowl,
      Self::RuddyDuck => &NestType::Platform,
      Self::SandhillCrane => &NestType::Ground,
      Self::SavannahSparrow => &NestType::Ground,
      Self::SaysPhoebe => &NestType::Bowl,
      Self::ScaledQuail => &NestType::Ground,
      Self::ScissorTailedFlycatcher => &NestType::Bowl,
      Self::SnowyEgret => &NestType::Platform,
      Self::SongSparrow => &NestType::Bowl,
      Self::SpottedOwl => &NestType::Cavity,
      Self::SpottedSandpiper => &NestType::Ground,
      Self::SpottedTowhee => &NestType::Ground,
      Self::SpraguesPipit => &NestType::Ground,
      Self::StellersJay => &NestType::Bowl,
      Self::SwainsonsHawk => &NestType::Platform,
      Self::TreeSwallow => &NestType::Cavity,
      Self::TrumpeterSwan => &NestType::Ground,
      Self::TuftedTitmouse => &NestType::Cavity,
      Self::TurkeyVulture => &NestType::Cavity,
      Self::VauxsSwift => &NestType::Cavity,
      Self::VioletGreenSwallow => &NestType::Cavity,
      Self::WesternMeadowlark => &NestType::Ground,
      Self::WesternTanager => &NestType::Bowl,
      Self::WhiteBreastedNuthatch => &NestType::Cavity,
      Self::WhiteCrownedSparrow => &NestType::Ground,
      Self::WhiteFacedIbis => &NestType::Platform,
      Self::WhiteThroatedSwift => &NestType::Cavity,
      Self::WhoopingCrane => &NestType::Ground,
      Self::WildTurkey => &NestType::Ground,
      Self::Willet => &NestType::Ground,
      Self::WilsonsSnipe => &NestType::Ground,
      Self::WoodDuck => &NestType::Cavity,
      Self::WoodStork => &NestType::Platform,
      Self::YellowBelliedSapsucker => &NestType::Cavity,
      Self::YellowBilledCuckoo => &NestType::Platform,
      Self::YellowBreastedChat => &NestType::Bowl,
      Self::YellowHeadedBlackbird => &NestType::Bowl,
      Self::YellowRumpedWarbler => &NestType::Bowl,
    }
  }

  pub fn is_predator(&self) -> bool {
    match self {
      Self::AcornWoodpecker => false,
      Self::AmericanAvocet => false,
      Self::AmericanBittern => false,
      Self::AmericanCoot => false,
      Self::AmericanCrow => false,
      Self::AmericanGoldfinch => false,
      Self::AmericanKestrel => true,
      Self::AmericanOystercatcher => false,
      Self::AmericanRedstart => false,
      Self::AmericanRobin => false,
      Self::AmericanWhitePelican => false,
      Self::AmericanWoodcock => false,
      Self::Anhinga => true,
      Self::AnnasHummingbird => false,
      Self::AshThroatedFlycatcher => false,
      Self::AtlanticPuffin => false,
      Self::BairdsSparrow => false,
      Self::BaldEagle => false,
      Self::BaltimoreOriole => false,
      Self::BarnOwl => true,
      Self::BarnSwallow => false,
      Self::BarredOwl => true,
      Self::BarrowsGoldeneye => false,
      Self::BellsVireo => false,
      Self::BeltedKingfisher => false,
      Self::BewicksWren => false,
      Self::BlackSkimmer => true,
      Self::BlackTern => false,
      Self::BlackVulture => false,
      Self::BlackBelliedWhistlingDuck => false,
      Self::BlackBilledMagpie => false,
      Self::BlackChinnedHummingbird => false,
      Self::BlackCrownedNightHeron => false,
      Self::BlackNeckedStilt => false,
      Self::BlueGrosbeak => false,
      Self::BlueJay => false,
      Self::BlueGrayGnatcatcher => false,
      Self::BlueWingedWarbler => false,
      Self::Bobolink => false,
      Self::Brant => false,
      Self::BrewersBlackbird => false,
      Self::BroadWingedHawk => true,
      Self::BronzedCowbird => false,
      Self::BrownPelican => false,
      Self::BrownHeadedCowbird => false,
      Self::BurrowingOwl => true,
      Self::Bushtit => false,
      Self::CaliforniaCondor => false,
      Self::CaliforniaQuail => false,
      Self::CanadaGoose => false,
      Self::Canvasback => false,
      Self::CarolinaChickadee => false,
      Self::CarolinaWren => false,
      Self::CassinsFinch => false,
      Self::CassinsSparrow => false,
      Self::CedarWaxwing => false,
      Self::CeruleanWarbler => false,
      Self::ChestnutCollaredLongspur => false,
      Self::ChihuahuanRaven => false,
      Self::ChimneySwift => false,
      Self::ChippingSparrow => false,
      Self::ClarksGrebe => false,
      Self::ClarksNutcracker => false,
      Self::CommonGrackle => false,
      Self::CommonLoon => false,
      Self::CommonMerganser => true,
      Self::CommonNighthawk => false,
      Self::CommonRaven => false,
      Self::CommonYellowthroat => false,
      Self::CoopersHawk => true,
      Self::DarkEyedJunco => false,
      Self::Dickcissel => false,
      Self::DoubleCrestedCormorant => false,
      Self::DownyWoodpecker => false,
      Self::EasternBluebird => false,
      Self::EasternKingbird => false,
      Self::EasternPhoebe => false,
      Self::EasternScreechOwl => true,
      Self::FerruginousHawk => true,
      Self::FishCrow => false,
      Self::ForstersTern => false,
      Self::FranklinsGull => false,
      Self::GoldenEagle => true,
      Self::GrasshopperSparrow => false,
      Self::GrayCatbird => false,
      Self::GreatBlueHeron => false,
      Self::GreatCrestedFlycatcher => false,
      Self::GreatEgret => false,
      Self::GreatHornedOwl => true,
      Self::GreaterPrairieChicken => false,
      Self::GreaterRoadrunner => true,
      Self::GreenHeron => false,
      Self::HermitThrush => false,
      Self::HoodedMerganser => false,
      Self::HoodedWarbler => false,
      Self::HornedLark => false,
      Self::HouseFinch => false,
      Self::HouseWren => false,
      Self::IncaDove => false,
      Self::IndigoBunting => false,
      Self::JuniperTitmouse => false,
      Self::Killdeer => false,
      Self::KingRail => false,
      Self::LazuliBunting => false,
      Self::LincolnsSparrow => false,
      Self::LoggerheadShrike => false,
      Self::Mallard => false,
      Self::MississippiKite => true,
      Self::MountainBluebird => false,
      Self::MountainChickadee => false,
      Self::MourningDove => false,
      Self::NorthernBobwhite => false,
      Self::NorthernCardinal => false,
      Self::NorthernFlicker => false,
      Self::NorthernHarrier => true,
      Self::NorthernMockingbird => false,
      Self::NorthernShoveler => false,
      Self::Osprey => false,
      Self::PaintedBunting => false,
      Self::PaintedWhitestart => false,
      Self::PeregrineFalcon => true,
      Self::PiedBilledGrebe => false,
      Self::PileatedWoodpecker => false,
      Self::PineSiskin => false,
      Self::ProthonotaryWarbler => false,
      Self::PurpleGallinule => false,
      Self::PurpleMartin => false,
      Self::PygmyNuthatch => false,
      Self::RedCrossbill => false,
      Self::RedBelliedWoodpecker => false,
      Self::RedBreastedMerganser => false,
      Self::RedBreastedNuthatch => false,
      Self::RedCockadedWoodpecker => false,
      Self::RedEyedVireo => false,
      Self::RedHeadedWoodpecker => false,
      Self::RedShoulderedHawk => true,
      Self::RedTailedHawk => true,
      Self::RedWingedBlackbird => false,
      Self::RingBilledGull => false,
      Self::RoseBreastedGrosbeak => false,
      Self::RoseateSpoonbill => false,
      Self::RubyCrownedKinglet => false,
      Self::RubyThroatedHummingbird => false,
      Self::RuddyDuck => false,
      Self::SandhillCrane => false,
      Self::SavannahSparrow => false,
      Self::SaysPhoebe => false,
      Self::ScaledQuail => false,
      Self::ScissorTailedFlycatcher => false,
      Self::SnowyEgret => true,
      Self::SongSparrow => false,
      Self::SpottedOwl => false,
      Self::SpottedSandpiper => false,
      Self::SpottedTowhee => false,
      Self::SpraguesPipit => false,
      Self::StellersJay => false,
      Self::SwainsonsHawk => true,
      Self::TreeSwallow => false,
      Self::TrumpeterSwan => false,
      Self::TuftedTitmouse => false,
      Self::TurkeyVulture => false,
      Self::VauxsSwift => false,
      Self::VioletGreenSwallow => false,
      Self::WesternMeadowlark => false,
      Self::WesternTanager => false,
      Self::WhiteBreastedNuthatch => false,
      Self::WhiteCrownedSparrow => false,
      Self::WhiteFacedIbis => true,
      Self::WhiteThroatedSwift => false,
      Self::WhoopingCrane => false,
      Self::WildTurkey => false,
      Self::Willet => true,
      Self::WilsonsSnipe => false,
      Self::WoodDuck => false,
      Self::WoodStork => false,
      Self::YellowBelliedSapsucker => false,
      Self::YellowBilledCuckoo => false,
      Self::YellowBreastedChat => false,
      Self::YellowHeadedBlackbird => false,
      Self::YellowRumpedWarbler => false,
    }
  }
}
