name: Lint

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  lint-python:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Lint rust
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings -D clippy::dbg_macro

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: install deps
        run: uv sync --dev

      - name: Lint python
        run: uv run pre-commit run -a
